name: ForceItemBattle
version: '${project.version}'
main: forceitembattle.ForceItemBattle
api-version: 1.18
commands:
  start:
    permission: battle.forceitem.command.start
  settings:
    permission: battle.forceitem.command.settings
  skip:
    permission: battle.forceitem.command.skip
  reset:
    permission: battle.forceitem.command.reset
  bp:
    aliases: [backpack]
  result:
  items:
  info:
  infowiki:
  spawn:
  bed:
  stoptimer:
    permission: battle.forceitem.command.stoptimer
